<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Image\Z.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data_Management_Warehouse\Data_Management_Warehouse.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="View\Page\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Image\Z.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
